### ISSUE TITLE
MVP, Schema, and Sample State Review

### ISSUE THREAD

**Issue by vawhitehouse** [tnizam/Animetsy#1]
# MVP
- [ ] How are you going to source your product listings? Will you create seeded data or use some external api?
- [x] #3 -> 'Multiple clickable list on one, to go to the main listing page.' I'm not quite sure what this is saying
- [x] #4 -> you have deleting items in cart twice
- [x] #5 -> I woud only focus on Reviews first. Comments can always be added in later as a bonus MVP.
- [x] Need to add 7th MVP (Production README)

# Schema
+ Users
  - [x] Etsy also asks for a first name when creating an account so you'll need a column for that
+ Reviews
  - [x] Same as with this MVP - just focus on `reviews` rather than `comments` (not sure if you're just using the two words interchangeably or if you were thinking you needed both)
+ Products
  - [x] You likely won't need an `image_url` - if you seed your product data, you'll use aws to store images, and if you use an external api you'll fetch the image from there
+ Cart
  - [x] A `cart` will have many `products` so you won't want a single `product_id`
- [x] You'll also need a joins table for cart products, since cart can have many products and a product can be in multiple carts

# Sample State 
- [x] This is frontend state so everything should be using camelCase
- [x] A cart will need to be keeping an array of `productIds` rather than a single `product_id`
- [x] Add in the other slices of state that you will likely need (errors, ui, session)
